/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:e2b0f5e0-637f-44d0-b6bd-1839f02545a8",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_qLvK1NNEo",
    "aws_user_pools_web_client_id": "g79aor0v4hsaod056qip71gdb",
    "oauth": {}
};


export default awsmobile;
